version: '2'
services:
  db-discord:
    container_name: db-discord
    hostname: db-discord
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    networks:
      - discord
    environment:
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: discord
      POSTGRES_DB: discord
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/discord-bot/postgresData/data:/var/lib/postgresql/data
    restart: always

  discord-music-bot:
    image: charlie67/discord-music-bot:xxxtest
    hostname: discord-music-bot
    container_name: discord-music-bot
    ports:
      - "8012:80"
    networks:
      - discord
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DISCORD_BOT_KEY=${DISCORD_BOT_KEY}
      - BOT_USER_ID=${BOT_USER_ID}
      - REDDIT_CLIENT_ID=HbzQBh3TD4losA
      - REDDIT_CLIENT_SECRET=CLHL-EBGUwqGwI4qKbm5sBBH6XEAZw
      - OWNER_ID=106139573561626624
      - POSTGRES_LOCATION=jdbc:postgresql://db-discord:5432/postgres
    restart: always
    
networks:
  discord:
    driver: bridge
