version: '2'
services:
  mongo-discord:
    image: mongo:latest
    hostname: mongo-discord
    container_name: mongo-discord
    ports:
    - 27017:27017
    volumes:
      - /opt/discord-bot/mongodata:/data/db